[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey =
PostUp = iptables -t nat -A PREROUTING -p tcp --dport 8123 -j DNAT --to-destination 10.13.13.2:8123
PostUp = iptables -t nat -A POSTROUTING -p tcp -d 10.13.13.2 --dport 8123 -j MASQUERADE
PostUp = iptables -t nat -A PREROUTING -p tcp --dport 9091 -j DNAT --to-destination 10.13.13.2:9091
PostUp = iptables -t nat -A POSTROUTING -p tcp -d 10.13.13.2 --dport 9091 -j MASQUERADE
PostUp = iptables -t nat -A PREROUTING -p tcp --dport 32400 -j DNAT --to-destination 10.13.13.2:32400
PostUp = iptables -t nat -A POSTROUTING -p tcp -d 10.13.13.2 --dport 32400 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 8123 -j DNAT --to-destination 10.13.13.2:8123
PostDown = iptables -t nat -D POSTROUTING -p tcp -d 10.13.13.2 --dport 8123 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 9091 -j DNAT --to-destination 10.13.13.2:9091
PostDown = iptables -t nat -D POSTROUTING -p tcp -d 10.13.13.2 --dport 9091 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 32400 -j DNAT --to-destination 10.13.13.2:32400
PostDown = iptables -t nat -D POSTROUTING -p tcp -d 10.13.13.2 --dport 32400 -j MASQUERADE

[Peer]
# peer_home
PublicKey =
PresharedKey =
AllowedIPs = 10.13.13.2/32
